# Generated by Django 5.2.1 on 2025-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loja_telefone_alter_loja_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='horario_funcionamento',
            field=models.CharField(blank=True, help_text='Ex: Seg–Sex 08:00–18:00; Sáb 08:00–12:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número de telefone para contato', max_length=20),
        ),
    ]
