# Generated by Django 5.2.1 on 2025-05-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='descricao',
            field=models.TextField(verbose_name='Breve descrição'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to=settings.AUTH_USER_MODEL),
        ),
    ]
