# Generated by Django 5.2.1 on 2025-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='loja',
            name='horario_funcionamento',
            field=models.CharField(blank=True, help_text='Ex: Seg-Sex 08:00-18:00; Sab 08:00-12:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone para contato'),
        ),
    ]
